language: ruby
branches:
  only:
    - master
rvm:
  - 2.4
  - 2.5
env: 
  - RAILS_ENV=test
services:
  - mysql
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver
before_install:
  - nvm install 8
  - nvm use 8
  - npm install -g yarn
  - mv ./.env.example ./.env
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - cp ./.travis.database.yml ./config/database.yml
  - node --version
  - npm --version
  - yarn --version
  - google-chrome --version
  - chromedriver --version
  - yarn install
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake parallel:spec
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
matrix:
  fast_finish: true
