language: ruby
branches:
  only:
    - master
rvm:
  - 2.4
  - 2.5
env: 
  - RAILS_ENV=test
services:
  - mysql
addons:
  chrome: stable
before_install:
  - nvm install 8
  - nvm use 8
  - npm install -g yarn
before_script:
  - mysql -e 'CREATE DATABASE sargantanacode_test;'
  - cp ./.travis.database.yml ./config/database.yml
  - node --version
  - npm --version
  - yarn --version
  - google-chrome --version
  - chromedriver --version
  - yarn install
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
